name: Node.js Package

on:
  release:
    types: [created]
  workflow_dispatch:

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - uses: actions/setup-node@v4
        with:
          node-version: 20
      - name: Install and Test
        # REMOVE the '#' below and update the folder name if your project is in a subfolder:
        # working-directory: ./your-subfolder-name 
        run: |
          npm ci
          npm test

  publish-npm:
    needs: build
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - uses: actions/setup-node@v4
        with:
          node-version: 20
          registry-url: https://registry.npmjs.org/
      - name: Install and Publish
        # REMOVE the '#' below and update the folder name if your project is in a subfolder:
        # working-directory: ./your-subfolder-name 
        run: |
          npm ci
          npm publish
        env:
          NODE_AUTH_TOKEN: ${{secrets.NPM_TOKEN}}
